export const ELIJO_CREER = [
    {
        title: "Efecto Retroactivo",
        content: "En 2021 ganamos la Copa América por 1-0 en la final y al año siguiente fuimos Campeones del Mundo. En 2024 repetimos exactamente el mismo patrón: Campeones de América por 1-0.",
        image: "copa-america.jpg",
        span: "col-span-1",
    },
    {
        title: "La Década de la Cuarta",
        content: "Las potencias que conquistaron su cuarta estrella histórica lo hicieron siempre en el segundo mundial de la década: Brasil en el 94, Italia en el 2006 y Alemania en 2014. El segundo de esta década es el nuestro.",
        image: "cuatro-estrellas.jpg",
        span: "col-span-1",
    },
    {
        title: "El Amuleto Canadiense",
        content: "En toda su historia, Canadá clasificó solo a tres mundiales: 1986 (Argentina campeón), 2022 (Argentina campeón) y ahora en 2026. Los antecedentes hablan por sí solos.",
        image: "canada.jpg",
        span: "col-span-1",
    },
    {
        title: "La Redención Matemática",
        content: "Italia perdió la final en el 94 y fue campeón 12 años después (2006). Alemania cayó en 2002 y festejó la cuarta 12 años después (2014). Argentina perdió en 2014... y en 2026 se cumple el ciclo exacto.",
        image: "finales-perdidas.jpg",
        span: "col-span-1",
    },
    {
        title: "El 2 a 0 Contra Honduras",
        content: "Argentina ganó su penúltimo amistoso de cara al mundial por dos goles de diferencia, igual que Brasil en 1962 ante Gales (3-1). Lautaro Martínez dio un gol y una asistencia, igual que Pelé en aquel partido. Y al igual que en Qatar 2022, Lautaro también asistió en el penúltimo amistoso, replicando el patrón de Pelé en 1958.",
        image: "honduras.jpg",
        span: "col-span-2",
    },
    {
        title: "Belgrano con la Selección Argentina",
        content: "Cada vez que Argentina sale campeona del mundo fuera del país, Belgrano se consagra campeón faltando menos de dos meses para el mundial ganando 3 a 2. En 1986 le ganó 3-2 a Olimpo, en 2022 le ganó 3-2 a Brown de Adrogué y en 2026 le ganó 3-2 a River. La máxima se cumple.",
        image: "belgrano.jpg",
        span: "col-span-2",
    },
    {
        title: "Carlos Alcaraz",
        content: "Cada vez que hubo un bicampeón mundial de fútbol, ese mismo año un jugador de tenis ganó su último Grand Slam pendiente, completando los cuatro. Lo que consiguió Alcaraz este año en Australia.",
        image: "alcaraz.jpg",
        span: "col-span-1",
    },
    {
        title: "Campeón de la Copa Africana",
        content: "El campeón de la Copa Africana previa al Mundial 2022 fue Senegal, el mismo que ganó el torneo previo al Mundial 2026. La única vez que una selección africana logró sus dos primeros títulos continentales en mundiales consecutivos fue entre 1958 y 1962: la última vez que hubo un bicampeón mundial, que fue Brasil.",
        image: "senegal.jpg",
        span: "col-span-1",
    },
    {
        title: "El Sorteo del Mundial",
        content: "Argentina juega el 16 y el 22 de junio, igual que en 1986. El partido del 22 contra Austria es a la misma hora que el partido ante Inglaterra en ese mundial. Alemania va al grupo E, igual que en 2022 y en 1986. La última final jugada a las 3 de la tarde hora local fue la de 1978.",
        image: "sorteo-mundial.jpg",
        span: "col-span-2",
    },
    {
        title: "Varias Coincidencias con 1986",
        content: "Corea del Sur va al grupo A. Paraguay comparte grupo con el local (EEUU), igual que en el 86 con México. Argelia comparte grupo con un sudamericano campeón, igual que en el 86. España enfrenta a un sudamericano campeón en Guadalajara, igual que cuando enfrentó a Brasil. Si Argentina termina primero y Uruguay segundo, se enfrentan en el primer cruce, como también ocurrió en ese mundial.",
        image: "mundial-1986.jpg",
        span: "col-span-2",
    },
    {
        title: "Coincidencias con el Mundial 2022",
        content: "Australia debuta contra un equipo europeo, igual que con Francia. El campeón africano comparte grupo con Ecuador. Portugal comparte grupo con el tercero de las eliminatorias europeas. Argentina enfrenta en grupos a una selección que compartió eliminatorias con San Marino: Polonia en 2022, Austria en 2026.",
        image: "mundial-2022.jpg",
        span: "col-span-1",
    },
    {
        title: "Coincidencias con el Mundial 1978",
        content: "Si Polonia clasifica, comparte grupo con Túnez. Brasil va al grupo C. Austria comparte grupo con el vigente campeón del mundo, igual que en el 78. Italia, si pasa, comparte grupos con un local. El finalista de la Eurocopa comparte grupo con el tercero del mundial anterior.",
        image: "mundial-1978.jpg",
        span: "col-span-1",
    },
    {
        title: "Coincidencias con el Mundial Sub-20 2007",
        content: "La última vez que Argentina fue bicampeón. Jordania juega un mundial por única vez, igual que entonces. Japón va al grupo F. Escocia y Austria comparten mundial por primera vez desde aquel torneo. El mundial se juega en Canadá. España y Uruguay comparten grupo. Estados Unidos está en el grupo D.",
        image: "sub-20-2007.jpg",
        span: "col-span-1",
    },
    {
        title: "Coincidencias con el Mundial Sub-20 1997",
        content: "Argentina fue bicampeón del mundo, que es lo que va a buscar ahora. Sudáfrica y Corea del Sur comparten grupo. Paraguay estuvo en el grupo D. El tercero del Sudamericano, Uruguay hoy y Paraguay entonces, comparte grupo con España.",
        image: "sub-20-1997.jpg",
        span: "col-span-1",
    },
    {
        title: "Clasificación de Curazao",
        content: "Brasil fue el último bicampeón en 1958 y 1962. Sus dos primeros resultados como local tras el título del 58 coinciden con los de Argentina tras 2022: 2-0 a Inglaterra (Brasil) y 2-0 a Panamá (Argentina); 7-0 a Chile (Brasil) y 7-0 a Curazao (Argentina).",
        image: "curazao.jpg",
        span: "col-span-1",
    },
    {
        title: "Nigeria",
        content: "La última vez que Nigeria, Serbia y Camerún no estuvieron en un mundial fue en 1986. Nigeria no jugó en 1978, en el 86, en 2022 ni jugará en 2026. Escocia y Austria jugaron el mundial de 1978 y vuelven a coincidir en este.",
        image: "nigeria.jpg",
        span: "col-span-1",
    },
    {
        title: "Turismo Carretera",
        content: "Mariano Werner ganó con Ford en el Oscar Cabalén, algo que no sucedía hacía 48 años, cuando lo logró Traverso en junio de 1977. Sí, también en junio, y también un año antes de que se jugara un mundial.",
        image: "turismo-carretera.jpg",
        span: "col-span-1",
    },
    {
        title: "Conexión Francesa",
        content: "En 1985: Platini gana el balón de oro y Argentina sale campeón en 1986. En 2022, Benzema gana el balón de oro y Argentina sale campeón en 2022. El último ganador del balón de oro fue el francés Ousmane Dembélé.",
        image: "dembele.jpg",
        span: "col-span-1",
    },
    {
        title: "El Elijo Creer de Messi",
        content: "En 2022 se lesionó faltando 2 semanas para el mundial, según los primeros exámenes no fue nada grave, podría jugar la copa del mundo. En 2026 se lesionó faltando 2 semanas para el mundial, según los exámenes podrá jugar el mundial y luchará por llevar a Argentina hasta el bicampeonato.",
        image: "messi.jpg",
        span: "col-span-2",
    },
];